#!/bin/sh
# PreToolUse hook: block Edit/Write/MultiEdit on generated protobuf code.
#
# Generated files under terminal_server/gen/ and terminal_client/lib/gen/ are
# regenerated by `make proto-generate` and hand-edits will be silently
# overwritten on the next regen. Tell the agent to edit the .proto instead.
#
# Reads tool-call JSON on stdin, writes a hook decision JSON on stdout, exits 0.

FILEPATH=$(jq -r '.tool_input.file_path // empty' 2>/dev/null)

case "$FILEPATH" in
    */terminal_server/gen/*|terminal_server/gen/*|*/terminal_client/lib/gen/*|terminal_client/lib/gen/*)
        cat <<'JSON'
{
  "hookSpecificOutput": {
    "hookEventName": "PreToolUse",
    "permissionDecision": "deny",
    "permissionDecisionReason": "This file is generated by `make proto-generate` from .proto sources in api/terminals/. Hand-edits will be overwritten. Edit the .proto and regenerate instead."
  }
}
JSON
        exit 0
        ;;
esac

exit 0
