version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/terminal_server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/terminal_client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

