name: terminal_client
description: Generic terminal client for the Terminals system.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  grpc: ^5.0.0
  protobuf: ^5.1.0
  fixnum: ^1.1.1
  multicast_dns: ^0.3.3
  flutter_webrtc: ^1.2.0
  qr_flutter: ^4.1.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
