package com.curtcox.terminals.android.diagnostics

import java.util.Calendar
import java.util.TimeZone

/** Mirrors Flutter [bugTokenWords] in `bug_report_chrome.dart` for cross-client bug token parity. */
internal val bugTokenWords: List<String> = listOf(
    "ace",
    "actor",
    "adapt",
    "air",
    "alert",
    "anchor",
    "angle",
    "apple",
    "artist",
    "asset",
    "audio",
    "autumn",
    "badge",
    "balance",
    "beam",
    "berry",
    "beyond",
    "bicycle",
    "bird",
    "blossom",
    "blue",
    "board",
    "book",
    "breeze",
    "bridge",
    "bright",
    "buffer",
    "button",
    "cable",
    "calm",
    "camera",
    "canvas",
    "captain",
    "carbon",
    "care",
    "center",
    "chapter",
    "check",
    "choice",
    "circle",
    "city",
    "clarity",
    "clock",
    "cloud",
    "coast",
    "color",
    "comfort",
    "compass",
    "control",
    "copper",
    "corner",
    "cotton",
    "craft",
    "credit",
    "crisp",
    "current",
    "cycle",
    "daily",
    "dawn",
    "delta",
    "design",
    "detail",
    "device",
    "dialog",
    "dock",
    "domain",
    "dream",
    "drift",
    "drive",
    "echo",
    "edge",
    "ember",
    "energy",
    "engine",
    "entry",
    "equal",
    "estate",
    "evening",
    "event",
    "fabric",
    "factor",
    "field",
    "filter",
    "final",
    "flame",
    "flight",
    "flower",
    "focus",
    "forest",
    "frame",
    "fresh",
    "future",
    "garden",
    "gentle",
    "glide",
    "glow",
    "gold",
    "grain",
    "graph",
    "green",
    "group",
    "guide",
    "habit",
    "harbor",
    "harmony",
    "haven",
    "hero",
    "horizon",
    "house",
    "idea",
    "image",
    "index",
    "island",
    "item",
    "jewel",
    "journey",
    "keeper",
    "key",
    "kind",
    "kit",
    "ladder",
    "lake",
    "launch",
    "layer",
    "leaf",
    "legend",
    "level",
    "light",
    "limit",
    "linen",
    "list",
    "logic",
    "lucky",
    "lumen",
    "maker",
    "map",
    "market",
    "matrix",
    "meadow",
    "memory",
    "metal",
    "method",
    "metric",
    "midday",
    "mind",
    "mirror",
    "model",
    "moment",
    "monsoon",
    "morning",
    "motion",
    "mountain",
    "music",
    "native",
    "nature",
    "network",
    "nexus",
    "night",
    "noble",
    "north",
    "note",
    "novel",
    "number",
    "oak",
    "object",
    "ocean",
    "offer",
    "omega",
    "onward",
    "orbit",
    "origin",
    "output",
    "packet",
    "page",
    "panel",
    "paper",
    "path",
    "pearl",
    "pencil",
    "pepper",
    "photo",
    "pixel",
    "planet",
    "plate",
    "point",
    "portal",
    "power",
    "prairie",
    "prime",
    "pulse",
    "quiet",
    "rapid",
    "reader",
    "record",
    "reef",
    "render",
    "report",
    "ribbon",
    "river",
    "rocket",
    "root",
    "round",
    "route",
    "sail",
    "sample",
    "scale",
    "scene",
    "screen",
    "script",
    "sea",
    "seed",
    "shadow",
    "signal",
    "silver",
    "simple",
    "sky",
    "smile",
    "snow",
    "solar",
    "source",
    "spark",
    "spirit",
    "spring",
    "square",
    "stable",
    "stage",
    "star",
    "stone",
    "storm",
    "story",
    "stream",
    "street",
    "studio",
    "summer",
    "sun",
    "sunset",
    "switch",
    "table",
    "target",
    "task",
    "tempo",
    "text",
    "thread",
    "timber",
    "today",
    "token",
    "tower",
    "trace",
    "track",
    "travel",
    "tree",
    "trust",
    "tunnel",
    "union",
    "unit",
    "update",
    "urban",
    "value",
    "vector",
    "velvet",
    "view",
    "vivid",
    "voice",
    "wave",
    "weather",
    "window",
    "winter",
    "wisdom",
    "wood",
    "world",
    "writer",
    "yard",
    "year",
    "yield",
    "young",
    "zenith",
    "zone",
)

data class BugIdentifier(
    val word: String,
    val code: String,
    val qrPayload: String,
)

/** Mirrors Flutter [buildBugIdentifier] using the same word list and index formula. */
fun buildBugIdentifier(nowMillis: Long, zone: TimeZone = TimeZone.getDefault()): BugIdentifier {
    val cal = Calendar.getInstance(zone)
    cal.timeInMillis = nowMillis
    val hour = cal.get(Calendar.HOUR_OF_DAY)
    val minute = cal.get(Calendar.MINUTE)
    val second = cal.get(Calendar.SECOND)
    val year = cal.get(Calendar.YEAR)
    val month = cal.get(Calendar.MONTH) + 1
    val day = cal.get(Calendar.DAY_OF_MONTH)
    val secondsFromMidnight = hour * 3600 + minute * 60 + second
    val daySalt = year * 10000 + month * 100 + day
    val index = ((secondsFromMidnight / 17) + daySalt) % bugTokenWords.size
    val word = bugTokenWords[index]
    val hh = hour.toString().padStart(2, '0')
    val mm = minute.toString().padStart(2, '0')
    val ss = second.toString().padStart(2, '0')
    val code = "$hh$mm$ss-$word"
    return BugIdentifier(word = word, code = code, qrPayload = "terminals-bug://$code")
}

/** Mirrors Flutter [sanitizeBugReportIdComponent]. */
fun sanitizeBugReportIdComponent(value: String): String {
    var normalized =
        value.trim().lowercase()
            .replace(Regex("[^a-z0-9]+"), "-")
            .replace(Regex("^-+"), "")
            .replace(Regex("-+$"), "")
    if (normalized.isEmpty()) {
        normalized = "unknown"
    }
    return normalized
}

/** Mirrors Flutter [buildLocalBugReportId] (`clientbug-<utcMillis>-…`). */
fun buildLocalBugReportId(
    nowMillis: Long,
    identifier: BugIdentifier,
    reporterDeviceId: String,
    subjectDeviceId: String,
): String {
    val reporter = sanitizeBugReportIdComponent(reporterDeviceId)
    val subject = sanitizeBugReportIdComponent(subjectDeviceId)
    val code = sanitizeBugReportIdComponent(identifier.code)
    return "clientbug-$nowMillis-$reporter-$subject-$code"
}
