package com.curtcox.terminals.android.media

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.launch
import org.json.JSONObject
import org.webrtc.IceCandidate
import org.webrtc.MediaConstraints
import org.webrtc.PeerConnection
import org.webrtc.PeerConnectionFactory
import org.webrtc.SdpObserver
import org.webrtc.SessionDescription
import terminals.control.v1.Control
import terminals.io.v1.Io

/**
 * [AndroidLiveMediaSession] backed by `io.github.webrtc-sdk:android`. Manages one
 * [PeerConnection] per stream ID. Processes inbound WebRTC signals from the server
 * ([applyWebRtcSignal]) and forwards outbound signals (ICE candidates, SDP answer)
 * via [signalSender].
 *
 * Thread model: all public methods are called on the main-thread ViewModel coroutine.
 * [signalSender] is launched from WebRTC observer callbacks (arbitrary thread) via [scope].
 */
class WebRtcSdkLiveMediaSession(
    private val factory: PeerConnectionFactory,
    private val signalSender: suspend (Control.WebRTCSignal) -> Unit = {},
    private val scope: CoroutineScope,
    private val iceServers: List<PeerConnection.IceServer> = emptyList(),
) : AndroidLiveMediaSession {

    private val sessions = HashMap<String, PeerConnection>()

    override fun applyStartStream(start: Io.StartStream): LiveMediaSessionResult {
        val streamId = start.streamId.trim()
        return when {
            streamId.isEmpty() -> LiveMediaSessionResult.Unsupported("empty-stream-id")
            sessions.containsKey(streamId) -> LiveMediaSessionResult.Applied
            else -> {
                val pc = factory.createPeerConnection(
                    PeerConnection.RTCConfiguration(iceServers),
                    SignalingObserver(streamId),
                )
                if (pc != null) {
                    sessions[streamId] = pc
                    LiveMediaSessionResult.Applied
                } else {
                    LiveMediaSessionResult.Unsupported("peer-connection-create-failed")
                }
            }
        }
    }

    override fun applyStopStream(streamId: String): LiveMediaSessionResult {
        sessions.remove(streamId.trim())?.dispose()
        return LiveMediaSessionResult.Applied
    }

    override fun applyRouteStream(route: Io.RouteStream): LiveMediaSessionResult =
        LiveMediaSessionResult.Applied

    override fun applyWebRtcSignal(signal: Control.WebRTCSignal): LiveMediaSessionResult {
        val pc = sessions[signal.streamId.trim()] ?: return LiveMediaSessionResult.Applied
        when (signal.signalTypeEnum) {
            Control.WebRTCSignalType.WEB_RTC_SIGNAL_TYPE_OFFER ->
                pc.setRemoteDescription(
                    AnswerCreatingSdpObserver(signal.streamId.trim(), pc),
                    SessionDescription(SessionDescription.Type.OFFER, signal.payload),
                )
            Control.WebRTCSignalType.WEB_RTC_SIGNAL_TYPE_ANSWER ->
                pc.setRemoteDescription(
                    NoOpSdpObserver(),
                    SessionDescription(SessionDescription.Type.ANSWER, signal.payload),
                )
            Control.WebRTCSignalType.WEB_RTC_SIGNAL_TYPE_ICE_CANDIDATE ->
                parseIceCandidate(signal.payload)?.let { pc.addIceCandidate(it) }
            else -> {}
        }
        return LiveMediaSessionResult.Applied
    }

    override fun stopLocalCaptureStreamsForPrivacy() {
        sessions.values.forEach { pc ->
            runCatching {
                pc.senders.forEach { sender -> sender.track()?.setEnabled(false) }
            }
        }
    }

    private fun parseIceCandidate(payload: String): IceCandidate? =
        runCatching {
            val obj = JSONObject(payload)
            IceCandidate(
                obj.getString("sdpMid"),
                obj.getInt("sdpMLineIndex"),
                obj.getString("candidate"),
            )
        }.getOrNull()

    private fun buildIceCandidatePayload(candidate: IceCandidate): String =
        JSONObject()
            .put("sdpMid", candidate.sdpMid)
            .put("sdpMLineIndex", candidate.sdpMLineIndex)
            .put("candidate", candidate.sdp)
            .toString()

    /** Forwards ICE candidates generated by this peer connection to the server. */
    @Suppress("TooManyFunctions")
    private inner class SignalingObserver(private val streamId: String) : PeerConnection.Observer {
        override fun onIceCandidate(candidate: IceCandidate?) {
            candidate ?: return
            val signal = Control.WebRTCSignal.newBuilder()
                .setStreamId(streamId)
                .setSignalTypeEnum(Control.WebRTCSignalType.WEB_RTC_SIGNAL_TYPE_ICE_CANDIDATE)
                .setPayload(buildIceCandidatePayload(candidate))
                .build()
            scope.launch { signalSender(signal) }
        }

        override fun onSignalingChange(state: PeerConnection.SignalingState?) = Unit
        override fun onIceConnectionChange(state: PeerConnection.IceConnectionState?) = Unit
        override fun onIceConnectionReceivingChange(receiving: Boolean) = Unit
        override fun onIceGatheringChange(state: PeerConnection.IceGatheringState?) = Unit
        override fun onIceCandidatesRemoved(candidates: Array<out IceCandidate>?) = Unit

        @Suppress("OVERRIDE_DEPRECATION")
        override fun onAddStream(stream: org.webrtc.MediaStream?) = Unit

        @Suppress("OVERRIDE_DEPRECATION")
        override fun onRemoveStream(stream: org.webrtc.MediaStream?) = Unit
        override fun onDataChannel(channel: org.webrtc.DataChannel?) = Unit
        override fun onRenegotiationNeeded() = Unit
        override fun onAddTrack(
            receiver: org.webrtc.RtpReceiver?,
            streams: Array<out org.webrtc.MediaStream>?,
        ) = Unit
    }

    /**
     * After [PeerConnection.setRemoteDescription] succeeds for an OFFER, creates an SDP answer,
     * sets it as the local description, and sends it to the server via [signalSender].
     */
    private inner class AnswerCreatingSdpObserver(
        private val streamId: String,
        private val pc: PeerConnection,
    ) : SdpObserver {
        override fun onSetSuccess() {
            pc.createAnswer(
                object : SdpObserver {
                    override fun onCreateSuccess(answer: SessionDescription?) {
                        answer ?: return
                        pc.setLocalDescription(NoOpSdpObserver(), answer)
                        val signal = Control.WebRTCSignal.newBuilder()
                            .setStreamId(streamId)
                            .setSignalTypeEnum(Control.WebRTCSignalType.WEB_RTC_SIGNAL_TYPE_ANSWER)
                            .setPayload(answer.description)
                            .build()
                        scope.launch { signalSender(signal) }
                    }
                    override fun onSetSuccess() = Unit
                    override fun onCreateFailure(error: String?) = Unit
                    override fun onSetFailure(error: String?) = Unit
                },
                MediaConstraints(),
            )
        }
        override fun onCreateSuccess(sdp: SessionDescription?) = Unit
        override fun onCreateFailure(error: String?) = Unit
        override fun onSetFailure(error: String?) = Unit
    }

    private class NoOpSdpObserver : SdpObserver {
        override fun onCreateSuccess(sdp: SessionDescription?) = Unit
        override fun onSetSuccess() = Unit
        override fun onCreateFailure(error: String?) = Unit
        override fun onSetFailure(error: String?) = Unit
    }
}
