run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - errcheck
    - exhaustive
    - gocritic
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unused
