run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - errcheck
    - exhaustive
    - gocritic
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unused

issues:
  exclude-use-default: false

