// Command term provides app runtime helper commands.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/curtcox/terminals/terminal_server/internal/appruntime"
)

func main() {
	code := run(os.Args[1:], os.Stdout, os.Stderr)
	if code != 0 {
		os.Exit(code)
	}
}

func run(args []string, stdout, stderr io.Writer) int {
	if len(args) < 1 {
		printUsage(stderr)
		return 2
	}
	top := strings.TrimSpace(args[0])
	switch top {
	case "app":
		return runApp(args[1:], stdout, stderr)
	case "sim":
		return runSim(args[1:], stdout, stderr)
	default:
		fmt.Fprintf(stderr, "unknown command group: %s\n", top)
		printUsage(stderr)
		return 2
	}
}

func runApp(args []string, stdout, stderr io.Writer) int {
	if len(args) < 2 {
		fmt.Fprintln(stderr, "usage: term app <new|check|test|load|reload|rollback|logs|trace> <name>")
		return 2
	}
	command := strings.TrimSpace(args[0])
	name := strings.TrimSpace(args[1])
	if name == "" {
		fmt.Fprintln(stderr, "missing app name")
		return 2
	}

	root := filepath.Join("apps", name)
	switch command {
	case "new":
		if err := os.MkdirAll(root, 0o755); err != nil {
			return fail(stderr, err)
		}
		if err := writeIfMissing(filepath.Join(root, "manifest.toml"), []byte(
			fmt.Sprintf("name = %q\nversion = %q\nlanguage = %q\ndescription = %q\n",
				name, "0.1.0", appruntime.LanguageTALV1, "Generated by term app new"),
		)); err != nil {
			return fail(stderr, err)
		}
		if err := writeIfMissing(filepath.Join(root, "main.tal"), []byte("def on_start():\n  pass\n")); err != nil {
			return fail(stderr, err)
		}
		fmt.Fprintf(stdout, "created app scaffold at %s\n", root)
		return 0
	case "check", "load":
		runtime := appruntime.NewRuntime()
		pkg, err := runtime.LoadPackage(context.Background(), root)
		if err != nil {
			return fail(stderr, err)
		}
		fmt.Fprintf(stdout, "%s ok: %s@%s\n", command, pkg.Manifest.Name, pkg.Manifest.Version)
		return 0
	case "test":
		runtime := appruntime.NewRuntime()
		pkg, err := runtime.LoadPackage(context.Background(), root)
		if err != nil {
			return fail(stderr, err)
		}
		testFiles, err := filepath.Glob(filepath.Join(root, "tests", "*_test.tal"))
		if err != nil {
			return fail(stderr, err)
		}
		sort.Strings(testFiles)
		fmt.Fprintf(stdout, "test ok: %s@%s\n", pkg.Manifest.Name, pkg.Manifest.Version)
		if len(testFiles) == 0 {
			fmt.Fprintln(stdout, "tests: none found (*.tal in apps/<name>/tests/")
			return 0
		}
		fmt.Fprintf(stdout, "tests: %d file(s)\n", len(testFiles))
		for _, file := range testFiles {
			fmt.Fprintf(stdout, "- %s\n", file)
		}
		return 0
	case "reload", "rollback":
		result, err := postAdminAppCommand(command, name)
		if err != nil {
			if command == "reload" {
				runtime := appruntime.NewRuntime()
				if _, loadErr := runtime.LoadPackage(context.Background(), root); loadErr != nil {
					return fail(stderr, loadErr)
				}
				if _, changed, reloadErr := runtime.ReloadPackage(context.Background(), name); reloadErr != nil {
					return fail(stderr, reloadErr)
				} else if changed {
					fmt.Fprintf(stdout, "reload ok: %s changed (local runtime)\n", name)
				} else {
					fmt.Fprintf(stdout, "reload ok: %s unchanged (local runtime)\n", name)
				}
				return 0
			}
			return fail(stderr, err)
		}
		fmt.Fprintf(stdout, "%s ok: %s@%s r%.0f\n", command, name, result["version"], toFloat(result["revision"]))
		return 0
	case "logs":
		payload, err := getAdminJSON("/admin/api/apps")
		if err != nil {
			return fail(stderr, err)
		}
		apps, _ := payload["apps"].([]any)
		for _, app := range apps {
			row, ok := app.(map[string]any)
			if !ok {
				continue
			}
			if strings.TrimSpace(toString(row["name"])) != name {
				continue
			}
			b, _ := json.MarshalIndent(row, "", "  ")
			fmt.Fprintln(stdout, string(b))
			return 0
		}
		return fail(stderr, fmt.Errorf("app %q not found", name))
	case "trace":
		payload, err := getAdminJSON("/admin/api/activations")
		if err != nil {
			return fail(stderr, err)
		}
		eventTail, ok := payload["event_tail"]
		if !ok {
			fmt.Fprintln(stdout, "[]")
			return 0
		}
		b, _ := json.MarshalIndent(eventTail, "", "  ")
		fmt.Fprintln(stdout, string(b))
		return 0
	default:
		fmt.Fprintf(stderr, "unknown app command: %s\n", command)
		return 2
	}
}

func runSim(args []string, stdout, stderr io.Writer) int {
	if len(args) < 1 || strings.TrimSpace(args[0]) != "run" {
		fmt.Fprintln(stderr, "usage: term sim run <app-name> --fixture <path>")
		return 2
	}
	if len(args) < 2 {
		fmt.Fprintln(stderr, "missing app name")
		return 2
	}
	name := strings.TrimSpace(args[1])
	if name == "" {
		fmt.Fprintln(stderr, "missing app name")
		return 2
	}
	fixturePath, err := parseFixtureFlag(args[2:])
	if err != nil {
		return fail(stderr, err)
	}
	if _, err := os.Stat(fixturePath); err != nil {
		return fail(stderr, fmt.Errorf("fixture not found: %w", err))
	}

	root := filepath.Join("apps", name)
	runtime := appruntime.NewRuntime()
	pkg, err := runtime.LoadPackage(context.Background(), root)
	if err != nil {
		return fail(stderr, err)
	}

	fmt.Fprintf(stdout, "sim run ok: app=%s version=%s fixture=%s\n", pkg.Manifest.Name, pkg.Manifest.Version, fixturePath)
	return 0
}

func parseFixtureFlag(args []string) (string, error) {
	for idx := 0; idx < len(args); idx++ {
		if strings.TrimSpace(args[idx]) != "--fixture" {
			continue
		}
		next := idx + 1
		if next >= len(args) || strings.TrimSpace(args[next]) == "" {
			return "", fmt.Errorf("--fixture requires a value")
		}
		return strings.TrimSpace(args[next]), nil
	}
	return "", fmt.Errorf("missing required --fixture <path>")
}

func getAdminJSON(path string) (map[string]any, error) {
	baseURL := strings.TrimSpace(os.Getenv("TERM_ADMIN_URL"))
	if baseURL == "" {
		baseURL = "http://127.0.0.1:50053"
	}
	resp, err := http.Get(strings.TrimRight(baseURL, "/") + path)
	if err != nil {
		return nil, err
	}
	defer func() {
		_ = resp.Body.Close()
	}()
	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	payload := map[string]any{}
	if len(raw) > 0 {
		if err := json.Unmarshal(raw, &payload); err != nil {
			return nil, err
		}
	}
	if resp.StatusCode >= 300 {
		if errText, ok := payload["error"].(string); ok && strings.TrimSpace(errText) != "" {
			return nil, errors.New(errText)
		}
		return nil, fmt.Errorf("admin request failed with status %d", resp.StatusCode)
	}
	return payload, nil
}

func postAdminAppCommand(command, app string) (map[string]any, error) {
	action := strings.TrimSpace(strings.ToLower(command))
	if action != "reload" && action != "rollback" {
		return nil, fmt.Errorf("unsupported app command %q", command)
	}
	baseURL := strings.TrimSpace(os.Getenv("TERM_ADMIN_URL"))
	if baseURL == "" {
		baseURL = "http://127.0.0.1:50053"
	}
	body := url.Values{}
	body.Set("app", strings.TrimSpace(app))
	req, err := http.NewRequest(http.MethodPost, strings.TrimRight(baseURL, "/")+"/admin/api/apps/"+action, strings.NewReader(body.Encode()))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer func() {
		_ = resp.Body.Close()
	}()
	payload := map[string]any{}
	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	if len(raw) > 0 {
		if err := json.Unmarshal(raw, &payload); err != nil {
			return nil, err
		}
	}
	if resp.StatusCode >= 300 {
		if errText, ok := payload["error"].(string); ok && strings.TrimSpace(errText) != "" {
			return nil, errors.New(errText)
		}
		return nil, fmt.Errorf("admin request failed with status %d", resp.StatusCode)
	}
	return payload, nil
}

func toFloat(v any) float64 {
	switch x := v.(type) {
	case float64:
		return x
	case int:
		return float64(x)
	case int64:
		return float64(x)
	default:
		return 0
	}
}

func toString(v any) string {
	s, _ := v.(string)
	return s
}

func writeIfMissing(path string, payload []byte) error {
	if _, err := os.Stat(path); err == nil {
		return nil
	}
	if err := os.WriteFile(path, payload, 0o644); err != nil {
		return err
	}
	return nil
}

func fail(stderr io.Writer, err error) int {
	fmt.Fprintln(stderr, err)
	return 1
}

func printUsage(stderr io.Writer) {
	fmt.Fprintln(stderr, "usage:")
	fmt.Fprintln(stderr, "  term app <new|check|test|load|reload|rollback|logs|trace> <name>")
	fmt.Fprintln(stderr, "  term sim run <app-name> --fixture <path>")
}
