// Command term provides app runtime helper commands.
package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/curtcox/terminals/terminal_server/internal/appruntime"
)

func main() {
	if len(os.Args) < 3 || strings.TrimSpace(os.Args[1]) != "app" {
		fmt.Fprintln(os.Stderr, "usage: term app <new|check|load|reload> <name>")
		os.Exit(2)
	}
	command := strings.TrimSpace(os.Args[2])
	name := ""
	if len(os.Args) > 3 {
		name = strings.TrimSpace(os.Args[3])
	}
	if name == "" {
		fmt.Fprintln(os.Stderr, "missing app name")
		os.Exit(2)
	}

	root := filepath.Join("apps", name)
	switch command {
	case "new":
		if err := os.MkdirAll(root, 0o755); err != nil {
			fatal(err)
		}
		writeIfMissing(filepath.Join(root, "manifest.toml"), []byte(
			fmt.Sprintf("name = %q\nversion = %q\nlanguage = %q\ndescription = %q\n",
				name, "0.1.0", "tal/1", "Generated by term app new"),
		))
		writeIfMissing(filepath.Join(root, "main.tal"), []byte("def on_start():\n  pass\n"))
		fmt.Printf("created app scaffold at %s\n", root)
	case "check", "load":
		runtime := appruntime.NewRuntime()
		pkg, err := runtime.LoadPackage(context.Background(), root)
		if err != nil {
			fatal(err)
		}
		fmt.Printf("%s ok: %s@%s\n", command, pkg.Manifest.Name, pkg.Manifest.Version)
	case "reload":
		runtime := appruntime.NewRuntime()
		if _, err := runtime.LoadPackage(context.Background(), root); err != nil {
			fatal(err)
		}
		if _, changed, err := runtime.ReloadPackage(context.Background(), name); err != nil {
			fatal(err)
		} else if changed {
			fmt.Printf("reload ok: %s changed\n", name)
		} else {
			fmt.Printf("reload ok: %s unchanged\n", name)
		}
	default:
		fmt.Fprintf(os.Stderr, "unknown app command: %s\n", command)
		os.Exit(2)
	}
}

func writeIfMissing(path string, payload []byte) {
	if _, err := os.Stat(path); err == nil {
		return
	}
	if err := os.WriteFile(path, payload, 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
