// Command term provides app runtime helper commands.
package main

import (
	"bufio"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"os/signal"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/curtcox/terminals/terminal_server/internal/appruntime"
	"github.com/curtcox/terminals/terminal_server/internal/eventlog/query"
)

var adminHTTPClient = http.DefaultClient

func main() {
	code := run(os.Args[1:], os.Stdout, os.Stderr)
	if code != 0 {
		os.Exit(code)
	}
}

func run(args []string, stdout, stderr io.Writer) int {
	if len(args) < 1 {
		printUsage(stderr)
		return 2
	}
	top := strings.TrimSpace(args[0])
	switch top {
	case "app":
		return runApp(args[1:], stdout, stderr)
	case "logs":
		return runLogs(args[1:], stdout, stderr)
	case "sim":
		return runSim(args[1:], stdout, stderr)
	default:
		fmt.Fprintf(stderr, "unknown command group: %s\n", top)
		printUsage(stderr)
		return 2
	}
}

func runApp(args []string, stdout, stderr io.Writer) int {
	if len(args) < 2 {
		fmt.Fprintln(stderr, "usage: term app <new|check|test|load|reload|rollback|logs|trace> <name>")
		return 2
	}
	command := strings.TrimSpace(args[0])
	name := strings.TrimSpace(args[1])
	if name == "" {
		fmt.Fprintln(stderr, "missing app name")
		return 2
	}

	root := filepath.Join("apps", name)
	switch command {
	case "new":
		if err := os.MkdirAll(root, 0o755); err != nil {
			return fail(stderr, err)
		}
		if err := writeIfMissing(filepath.Join(root, "manifest.toml"), []byte(
			fmt.Sprintf("name = %q\nversion = %q\nlanguage = %q\ndescription = %q\n",
				name, "0.1.0", appruntime.LanguageTALV1, "Generated by term app new"),
		)); err != nil {
			return fail(stderr, err)
		}
		if err := writeIfMissing(filepath.Join(root, "main.tal"), []byte("def on_start():\n  pass\n")); err != nil {
			return fail(stderr, err)
		}
		fmt.Fprintf(stdout, "created app scaffold at %s\n", root)
		return 0
	case "check", "load":
		runtime := appruntime.NewRuntime()
		pkg, err := runtime.LoadPackage(context.Background(), root)
		if err != nil {
			return fail(stderr, err)
		}
		fmt.Fprintf(stdout, "%s ok: %s@%s\n", command, pkg.Manifest.Name, pkg.Manifest.Version)
		return 0
	case "test":
		runtime := appruntime.NewRuntime()
		pkg, err := runtime.LoadPackage(context.Background(), root)
		if err != nil {
			return fail(stderr, err)
		}
		testFiles, err := filepath.Glob(filepath.Join(root, "tests", "*_test.tal"))
		if err != nil {
			return fail(stderr, err)
		}
		sort.Strings(testFiles)
		fmt.Fprintf(stdout, "test ok: %s@%s\n", pkg.Manifest.Name, pkg.Manifest.Version)
		if len(testFiles) == 0 {
			fmt.Fprintln(stdout, "tests: none found (*.tal in apps/<name>/tests/")
			return 0
		}
		fmt.Fprintf(stdout, "tests: %d file(s)\n", len(testFiles))
		for _, file := range testFiles {
			fmt.Fprintf(stdout, "- %s\n", file)
		}
		return 0
	case "reload", "rollback":
		result, err := postAdminAppCommand(command, name)
		if err != nil {
			if command == "reload" {
				runtime := appruntime.NewRuntime()
				if _, loadErr := runtime.LoadPackage(context.Background(), root); loadErr != nil {
					return fail(stderr, loadErr)
				}
				if _, changed, reloadErr := runtime.ReloadPackage(context.Background(), name); reloadErr != nil {
					return fail(stderr, reloadErr)
				} else if changed {
					fmt.Fprintf(stdout, "reload ok: %s changed (local runtime)\n", name)
				} else {
					fmt.Fprintf(stdout, "reload ok: %s unchanged (local runtime)\n", name)
				}
				return 0
			}
			return fail(stderr, err)
		}
		fmt.Fprintf(stdout, "%s ok: %s@%s r%.0f\n", command, name, result["version"], toFloat(result["revision"]))
		return 0
	case "logs":
		payload, err := getAdminJSON("/admin/api/apps")
		if err != nil {
			return fail(stderr, err)
		}
		apps, _ := payload["apps"].([]any)
		for _, app := range apps {
			row, ok := app.(map[string]any)
			if !ok {
				continue
			}
			if strings.TrimSpace(toString(row["name"])) != name {
				continue
			}
			b, _ := json.MarshalIndent(row, "", "  ")
			fmt.Fprintln(stdout, string(b))
			return 0
		}
		return fail(stderr, fmt.Errorf("app %q not found", name))
	case "trace":
		payload, err := getAdminJSON("/admin/api/activations")
		if err != nil {
			return fail(stderr, err)
		}
		eventTail, ok := payload["event_tail"]
		if !ok {
			fmt.Fprintln(stdout, "[]")
			return 0
		}
		b, _ := json.MarshalIndent(eventTail, "", "  ")
		fmt.Fprintln(stdout, string(b))
		return 0
	default:
		fmt.Fprintf(stderr, "unknown app command: %s\n", command)
		return 2
	}
}

func runSim(args []string, stdout, stderr io.Writer) int {
	if len(args) < 1 || strings.TrimSpace(args[0]) != "run" {
		fmt.Fprintln(stderr, "usage: term sim run <app-name> --fixture <path>")
		return 2
	}
	if len(args) < 2 {
		fmt.Fprintln(stderr, "missing app name")
		return 2
	}
	name := strings.TrimSpace(args[1])
	if name == "" {
		fmt.Fprintln(stderr, "missing app name")
		return 2
	}
	fixturePath, err := parseFixtureFlag(args[2:])
	if err != nil {
		return fail(stderr, err)
	}
	if _, err := os.Stat(fixturePath); err != nil {
		return fail(stderr, fmt.Errorf("fixture not found: %w", err))
	}

	root := filepath.Join("apps", name)
	runtime := appruntime.NewRuntime()
	pkg, err := runtime.LoadPackage(context.Background(), root)
	if err != nil {
		return fail(stderr, err)
	}

	fmt.Fprintf(stdout, "sim run ok: app=%s version=%s fixture=%s\n", pkg.Manifest.Name, pkg.Manifest.Version, fixturePath)
	return 0
}

func runLogs(args []string, stdout, stderr io.Writer) int {
	if len(args) < 1 {
		fmt.Fprintln(stderr, "usage: term logs <tail|search|trace|activation|stats> [filters...]")
		return 2
	}
	cmd := strings.TrimSpace(strings.ToLower(args[0]))
	rest := append([]string(nil), args[1:]...)
	opts := logsOptions{
		dir: defaultLogDir(),
		n:   50,
	}
	for len(rest) > 0 {
		token := strings.TrimSpace(rest[0])
		switch {
		case token == "--json":
			opts.json = true
			rest = rest[1:]
		case token == "--follow":
			opts.follow = true
			rest = rest[1:]
		case token == "--since" && len(rest) >= 2:
			opts.since = strings.TrimSpace(rest[1])
			rest = rest[2:]
		case strings.HasPrefix(token, "--since="):
			opts.since = strings.TrimSpace(strings.TrimPrefix(token, "--since="))
			rest = rest[1:]
		case token == "--dir" && len(rest) >= 2:
			opts.dir = strings.TrimSpace(rest[1])
			rest = rest[2:]
		case strings.HasPrefix(token, "--dir="):
			opts.dir = strings.TrimSpace(strings.TrimPrefix(token, "--dir="))
			rest = rest[1:]
		case token == "-n" && len(rest) >= 2:
			parsed, err := strconv.Atoi(strings.TrimSpace(rest[1]))
			if err != nil {
				return fail(stderr, fmt.Errorf("invalid -n value: %w", err))
			}
			opts.n = parsed
			rest = rest[2:]
		default:
			goto doneOpts
		}
	}
doneOpts:
	if opts.since != "" {
		rest = append(rest, "since="+opts.since)
	}
	if opts.dir == "" {
		opts.dir = defaultLogDir()
	}

	switch cmd {
	case "tail":
		records, err := query.Search(opts.dir, rest, time.Now().UTC())
		if err != nil {
			return fail(stderr, err)
		}
		if opts.n > 0 && len(records) > opts.n {
			records = records[len(records)-opts.n:]
		}
		if err := printRecords(stdout, records, opts.json); err != nil {
			return fail(stderr, err)
		}
		if !opts.follow {
			return 0
		}
		return followLogs(opts, rest, stdout, stderr, lastSeq(records))
	case "search":
		records, err := query.Search(opts.dir, rest, time.Now().UTC())
		if err != nil {
			return fail(stderr, err)
		}
		return finishPrint(stdout, stderr, records, opts.json)
	case "trace":
		if len(rest) < 1 || strings.TrimSpace(rest[0]) == "" {
			return fail(stderr, fmt.Errorf("usage: term logs trace <trace_id>"))
		}
		records, err := query.ReadAll(opts.dir)
		if err != nil {
			return fail(stderr, err)
		}
		traceRecords := query.Trace(records, strings.TrimSpace(rest[0]))
		if opts.json {
			return finishPrint(stdout, stderr, traceRecords, true)
		}
		return printTraceTree(stdout, traceRecords)
	case "activation":
		if len(rest) < 1 || strings.TrimSpace(rest[0]) == "" {
			return fail(stderr, fmt.Errorf("usage: term logs activation <activation_id>"))
		}
		records, err := query.ReadAll(opts.dir)
		if err != nil {
			return fail(stderr, err)
		}
		return finishPrint(stdout, stderr, query.Activation(records, strings.TrimSpace(rest[0])), opts.json)
	case "stats":
		by := "event"
		filters := make([]string, 0, len(rest))
		for i := 0; i < len(rest); i++ {
			token := strings.TrimSpace(rest[i])
			if strings.HasPrefix(token, "--by=") {
				by = strings.TrimSpace(strings.TrimPrefix(token, "--by="))
				continue
			}
			filters = append(filters, token)
		}
		records, err := query.Search(opts.dir, filters, time.Now().UTC())
		if err != nil {
			return fail(stderr, err)
		}
		stats := query.Stats(records, by)
		keys := make([]string, 0, len(stats))
		for key := range stats {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			fmt.Fprintf(stdout, "%s\t%d\n", key, stats[key])
		}
		return 0
	default:
		return fail(stderr, fmt.Errorf("unknown logs command: %s", cmd))
	}
}

type logsOptions struct {
	dir    string
	json   bool
	follow bool
	since  string
	n      int
}

func defaultLogDir() string {
	dir := strings.TrimSpace(os.Getenv("TERMINALS_LOG_DIR"))
	if dir == "" {
		dir = "logs"
	}
	return dir
}

func finishPrint(stdout, stderr io.Writer, records []query.Record, asJSON bool) int {
	if err := printRecords(stdout, records, asJSON); err != nil {
		return fail(stderr, err)
	}
	return 0
}

func printRecords(out io.Writer, records []query.Record, asJSON bool) error {
	w := bufio.NewWriter(out)
	for _, record := range records {
		if asJSON {
			encoded, _ := json.Marshal(record)
			if _, err := w.Write(encoded); err != nil {
				return err
			}
			if err := w.WriteByte('\n'); err != nil {
				return err
			}
			continue
		}
		line := formatRecord(record)
		if _, err := w.WriteString(line); err != nil {
			return err
		}
		if err := w.WriteByte('\n'); err != nil {
			return err
		}
	}
	return w.Flush()
}

func followLogs(opts logsOptions, filters []string, stdout, stderr io.Writer, startSeq uint64) int {
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()
	currentSeq := startSeq
	ticker := time.NewTicker(1 * time.Second)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return 0
		case <-ticker.C:
			records, err := query.Search(opts.dir, filters, time.Now().UTC())
			if err != nil {
				return fail(stderr, err)
			}
			newRows := make([]query.Record, 0, len(records))
			for _, record := range records {
				seq := recordSeq(record)
				if seq <= currentSeq {
					continue
				}
				newRows = append(newRows, record)
				if seq > currentSeq {
					currentSeq = seq
				}
			}
			if len(newRows) == 0 {
				continue
			}
			if err := printRecords(stdout, newRows, opts.json); err != nil {
				return fail(stderr, err)
			}
		}
	}
}

func formatRecord(record query.Record) string {
	ts := recString(record, "ts")
	level := recString(record, "level")
	component := recString(record, "component")
	event := recString(record, "event")
	msg := recString(record, "msg")
	activation := recString(record, "activation_id")
	trace := recString(record, "trace_id")
	seq := recString(record, "seq")
	parts := []string{fmt.Sprintf("ts=%s", ts), fmt.Sprintf("level=%s", level), fmt.Sprintf("seq=%s", seq), fmt.Sprintf("component=%s", component), fmt.Sprintf("event=%s", event)}
	if trace != "" {
		parts = append(parts, "trace="+trace)
	}
	if activation != "" {
		parts = append(parts, "activation="+activation)
	}
	if msg != "" {
		parts = append(parts, "msg="+strconv.Quote(msg))
	}
	return strings.Join(parts, " ")
}

func printTraceTree(out io.Writer, records []query.Record) int {
	children := make(map[string][]query.Record)
	roots := make([]query.Record, 0)
	for _, record := range records {
		parent := recString(record, "parent_span_id")
		if parent == "" {
			roots = append(roots, record)
			continue
		}
		children[parent] = append(children[parent], record)
	}
	w := bufio.NewWriter(out)
	for _, root := range roots {
		_ = writeTraceNode(w, root, children, 0)
	}
	_ = w.Flush()
	return 0
}

func writeTraceNode(w io.Writer, record query.Record, children map[string][]query.Record, depth int) error {
	prefix := strings.Repeat("  ", depth)
	if _, err := fmt.Fprintf(w, "%s%s\n", prefix, formatRecord(record)); err != nil {
		return err
	}
	spanID := recString(record, "span_id")
	if spanID == "" {
		return nil
	}
	for _, child := range children[spanID] {
		if err := writeTraceNode(w, child, children, depth+1); err != nil {
			return err
		}
	}
	return nil
}

func lastSeq(records []query.Record) uint64 {
	var max uint64
	for _, record := range records {
		if seq := recordSeq(record); seq > max {
			max = seq
		}
	}
	return max
}

func recordSeq(record query.Record) uint64 {
	switch v := record["seq"].(type) {
	case float64:
		return uint64(v)
	case int64:
		return uint64(v)
	case int:
		return uint64(v)
	case uint64:
		return v
	default:
		return 0
	}
}

func recString(record query.Record, key string) string {
	if v, ok := record[key]; ok {
		switch x := v.(type) {
		case string:
			return strings.TrimSpace(x)
		case float64:
			return strconv.FormatFloat(x, 'f', -1, 64)
		case int:
			return strconv.Itoa(x)
		}
	}
	return ""
}

func parseFixtureFlag(args []string) (string, error) {
	for idx := 0; idx < len(args); idx++ {
		if strings.TrimSpace(args[idx]) != "--fixture" {
			continue
		}
		next := idx + 1
		if next >= len(args) || strings.TrimSpace(args[next]) == "" {
			return "", fmt.Errorf("--fixture requires a value")
		}
		return strings.TrimSpace(args[next]), nil
	}
	return "", fmt.Errorf("missing required --fixture <path>")
}

func getAdminJSON(path string) (map[string]any, error) {
	baseURL := strings.TrimSpace(os.Getenv("TERM_ADMIN_URL"))
	if baseURL == "" {
		baseURL = "http://127.0.0.1:50053"
	}
	resp, err := adminHTTPClient.Get(strings.TrimRight(baseURL, "/") + path)
	if err != nil {
		return nil, err
	}
	defer func() {
		_ = resp.Body.Close()
	}()
	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	payload := map[string]any{}
	if len(raw) > 0 {
		if err := json.Unmarshal(raw, &payload); err != nil {
			return nil, err
		}
	}
	if resp.StatusCode >= 300 {
		if errText, ok := payload["error"].(string); ok && strings.TrimSpace(errText) != "" {
			return nil, errors.New(errText)
		}
		return nil, fmt.Errorf("admin request failed with status %d", resp.StatusCode)
	}
	return payload, nil
}

func postAdminAppCommand(command, app string) (map[string]any, error) {
	action := strings.TrimSpace(strings.ToLower(command))
	if action != "reload" && action != "rollback" {
		return nil, fmt.Errorf("unsupported app command %q", command)
	}
	baseURL := strings.TrimSpace(os.Getenv("TERM_ADMIN_URL"))
	if baseURL == "" {
		baseURL = "http://127.0.0.1:50053"
	}
	body := url.Values{}
	body.Set("app", strings.TrimSpace(app))
	req, err := http.NewRequest(http.MethodPost, strings.TrimRight(baseURL, "/")+"/admin/api/apps/"+action, strings.NewReader(body.Encode()))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := adminHTTPClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer func() {
		_ = resp.Body.Close()
	}()
	payload := map[string]any{}
	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	if len(raw) > 0 {
		if err := json.Unmarshal(raw, &payload); err != nil {
			return nil, err
		}
	}
	if resp.StatusCode >= 300 {
		if errText, ok := payload["error"].(string); ok && strings.TrimSpace(errText) != "" {
			return nil, errors.New(errText)
		}
		return nil, fmt.Errorf("admin request failed with status %d", resp.StatusCode)
	}
	return payload, nil
}

func toFloat(v any) float64 {
	switch x := v.(type) {
	case float64:
		return x
	case int:
		return float64(x)
	case int64:
		return float64(x)
	default:
		return 0
	}
}

func toString(v any) string {
	s, _ := v.(string)
	return s
}

func writeIfMissing(path string, payload []byte) error {
	if _, err := os.Stat(path); err == nil {
		return nil
	}
	if err := os.WriteFile(path, payload, 0o644); err != nil {
		return err
	}
	return nil
}

func fail(stderr io.Writer, err error) int {
	fmt.Fprintln(stderr, err)
	return 1
}

func printUsage(stderr io.Writer) {
	fmt.Fprintln(stderr, "usage:")
	fmt.Fprintln(stderr, "  term app <new|check|test|load|reload|rollback|logs|trace> <name>")
	fmt.Fprintln(stderr, "  term logs <tail|search|trace|activation|stats> [args]")
	fmt.Fprintln(stderr, "  term sim run <app-name> --fixture <path>")
}
