#!/usr/bin/env python3
"""Find tracked files in the repo that are 'too big' under various heuristics.

Surfaces files whose size suggests they should be split, refactored, moved to
git-lfs, or marked generated. Designed to be run standalone or invoked from
`scripts/next.py` as a drift signal alongside the existing un-validated use-
case, open-audit, and stale-plan signals.

Heuristics (intentionally local and fast — no remote calls, no git log walks):

1. Scope: tracked files only (`git ls-files`). Gitignored files are *not*
   scanned. Rationale: gitignored files are typically local build artifacts,
   generated output, or vendored binaries we have deliberately chosen not to
   track; their size is not actionable as code work.

2. Path-based skip patterns (SKIP_PATH_PATTERNS). Catches vendored code,
   build output that occasionally gets committed, generated protobuf
   bindings, lockfiles whose size is mechanical, and golden/fixture
   directories.

3. Content sniff: the first ~2 KiB is checked for generated-code markers
   (DO NOT EDIT, @generated, Code generated by, AUTO-GENERATED, ...). Files
   whose head matches are skipped even when the path didn't match — catches
   generated files that escape the path patterns.

4. Per-category thresholds. A 1500-line plan is normal-bad; a 1500-line
   shell script is alarming. Categories are picked by extension + path:

     plan      — plans/**/*.md
     doc       — any other *.md
     source    — *.go, *.kt, *.py, *.ts, *.tsx, *.dart, *.js, *.java, ...
     test      — files under test/ or tests/, or matching *_test.go,
                 *Test.kt, test_*.py, *.test.ts, *_test.dart, etc.
     config    — *.yaml, *.yml, *.json, *.toml, *.xml, *.proto
     shell     — *.sh, *.bash, *.zsh
     binary    — anything else (compared in bytes, not lines)

   Each category has a `warn` and `flag` threshold. Size >= warn is
   reported; size >= flag is marked severity:flag. Thresholds are picked
   from "what's a normal ceiling in this repo today" + headroom, not from
   an absolute principle — adjust them as the repo's norms shift.

5. Suggested action per category, so the agent reading the report knows
   what to do without re-deriving the intent. The suggestion is direction-
   bearing, not prescriptive (e.g. "split the plan or spawn a follow-up",
   not "delete lines"). Wrong-but-loud beats silent.

Output is markdown by default; pass `--json` for a machine-readable list.

Usage:
  python3 scripts/find-oversized-files.py
  python3 scripts/find-oversized-files.py --json
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Path patterns that are skipped wholesale.
#
# A pattern that starts or ends with "/" matches as a path *segment* in
# "/{rel}". Other patterns match as a substring of `rel` or as an `endswith`.
# Keep this list ordered by category for readability.
SKIP_PATH_PATTERNS = [
    # Vendored / external code we don't author.
    "vendor/", "node_modules/", "third_party/",
    # Build output that occasionally gets tracked.
    "build/", "dist/", ".gradle/", ".dart_tool/",
    # Generated protobuf / gRPC bindings (we own the .proto, not these).
    ".pb.go", ".pb.dart", "_pb2.py", "_pb2_grpc.py",
    ".pbobjc.h", ".pbobjc.m", "GrpcKt.kt", "Grpc.java",
    # Explicit generated dirs (some repos commit them).
    "/generated/", "/gen/",
    # Lockfiles: size is mechanical, not editorial.
    "go.sum", "package-lock.json", "pnpm-lock.yaml", "yarn.lock",
    "pubspec.lock", "Cargo.lock", "Gemfile.lock",
    # Golden / fixture directories: expected to be large.
    "/golden/", "/fixtures/", "/testdata/",
]

# Markers searched in the first 2 KiB of a file. Any hit -> treat as generated.
GENERATED_MARKERS = (
    b"DO NOT EDIT",
    b"@generated",
    b"Code generated by",
    b"AUTO-GENERATED",
    b"automatically generated",
    b"This file was automatically generated",
)

# Category thresholds. `unit` is "lines" for text or "bytes" for binary.
# `warn` = report at this size; `flag` = upgrade to severity:flag.
THRESHOLDS = {
    "plan":   {"unit": "lines", "warn":  800, "flag": 1500},
    "doc":    {"unit": "lines", "warn":  500, "flag": 1000},
    "source": {"unit": "lines", "warn":  600, "flag": 1200},
    "test":   {"unit": "lines", "warn": 1000, "flag": 2000},
    "config": {"unit": "lines", "warn":  400, "flag":  800},
    "shell":  {"unit": "lines", "warn":  300, "flag":  600},
    "binary": {"unit": "bytes", "warn": 512 * 1024, "flag": 2 * 1024 * 1024},
}

# What to do with a flagged file. Intent-bearing, not prescriptive.
SUGGESTIONS = {
    "plan":   "Split the plan or mark phases complete and spawn a follow-up plan.",
    "doc":    "Split into focused docs, or extract reference material into a sibling file.",
    "source": "Extract a module — group related types/functions and move them to a sibling file.",
    "test":   "Group tests into smaller files by feature area; large suites hide flakes and slow iteration.",
    "config": "Split config into per-area files or extract templates.",
    "shell":  "Extract helpers into a library file, or rewrite in Python under scripts/ for testability.",
    "binary": "Consider git-lfs, adding to .gitignore, or moving to an external artifact store.",
}

# Extensions used for source/config categorization. (Text-ness is implied by
# the category itself — anything not matched here that isn't .md/.sh falls
# through to "binary".)
SOURCE_EXTS = {
    ".go", ".kt", ".kts", ".py", ".ts", ".tsx", ".dart",
    ".js", ".jsx", ".java", ".rs", ".swift",
}
CONFIG_EXTS = {".yaml", ".yml", ".json", ".toml", ".xml", ".proto"}
SHELL_EXTS = {".sh", ".bash", ".zsh"}


def _ext(rel: str) -> str:
    base = rel.rsplit("/", 1)[-1]
    if "." not in base:
        return ""
    return "." + base.rsplit(".", 1)[-1].lower()


def categorize(rel: str) -> str:
    """Pick a category for a tracked file path. Order matters."""
    ext = _ext(rel)
    name = rel.rsplit("/", 1)[-1]

    # 1. Plans and other markdown.
    if ext == ".md":
        if rel.startswith("plans/"):
            return "plan"
        return "doc"

    # 2. Test files — match before generic source so a test in a source
    # ext (e.g. .kt) is reported under the more lenient test thresholds.
    test_markers = (
        "/test/" in f"/{rel}" or "/tests/" in f"/{rel}"
        or name.endswith("_test.go")
        or name.endswith("Test.kt") or name.endswith("Tests.kt")
        or name.startswith("test_") or name.endswith("_test.py")
        or name.endswith(".test.ts") or name.endswith(".spec.ts")
        or name.endswith(".test.tsx") or name.endswith(".spec.tsx")
        or name.endswith("_test.dart")
    )
    if test_markers:
        return "test"

    # 3. Shell / source / config by extension.
    if ext in SHELL_EXTS:
        return "shell"
    if ext in SOURCE_EXTS:
        return "source"
    if ext in CONFIG_EXTS:
        return "config"

    # 4. Anything else is treated as a binary blob for size purposes.
    return "binary"


def path_skipped(rel: str) -> bool:
    """True if `rel` matches any SKIP_PATH_PATTERNS entry."""
    framed = f"/{rel}"
    for pat in SKIP_PATH_PATTERNS:
        if pat.endswith("/") or pat.startswith("/"):
            # Treat as path segment match.
            if pat in framed:
                return True
        else:
            # Substring / suffix match.
            if pat in rel or rel.endswith(pat):
                return True
    return False


def looks_generated(path: Path) -> bool:
    """True if the file's first 2 KiB contains a generated-code marker.

    Cheap content sniff. Catches generated files that slipped past
    SKIP_PATH_PATTERNS (e.g. one-off codegen output placed outside a
    standard generated/ dir).
    """
    try:
        with path.open("rb") as f:
            head = f.read(2048)
    except OSError:
        return False
    return any(marker in head for marker in GENERATED_MARKERS)


def measure(path: Path, category: str) -> int:
    """Return the size value (lines or bytes) compared against thresholds."""
    if THRESHOLDS[category]["unit"] == "bytes":
        try:
            return path.stat().st_size
        except OSError:
            return 0
    # Line count via byte read — fast and tolerant of mixed line endings.
    try:
        with path.open("rb") as f:
            return sum(1 for _ in f)
    except OSError:
        return 0


def tracked_files() -> "list[str]":
    """Return repo-relative paths of all git-tracked files.

    Using `git ls-files` (instead of os.walk) automatically excludes
    gitignored paths and untracked files, which is the scope contract
    documented at the top of this script.
    """
    out = subprocess.run(
        ["git", "ls-files"],
        capture_output=True, text=True, check=True, cwd=REPO,
    )
    return [p for p in out.stdout.splitlines() if p]


def scan() -> "list[dict]":
    """Walk tracked files and return a sorted list of oversized hits.

    Each entry: {path, category, unit, size, warn, flag, severity, suggestion}.
    Sorted by severity (flag before warn), then by size descending.
    """
    results: list[dict] = []
    for rel in tracked_files():
        if path_skipped(rel):
            continue
        path = REPO / rel
        if not path.is_file():
            continue
        category = categorize(rel)
        thr = THRESHOLDS[category]
        # Generated-marker sniff only for text categories. Binary blobs
        # rarely carry ASCII headers we can match reliably, and we want
        # them flagged regardless (binary size is the whole point).
        if category != "binary" and looks_generated(path):
            continue
        size = measure(path, category)
        if size < thr["warn"]:
            continue
        severity = "flag" if size >= thr["flag"] else "warn"
        results.append({
            "path": rel,
            "category": category,
            "unit": thr["unit"],
            "size": size,
            "warn": thr["warn"],
            "flag": thr["flag"],
            "severity": severity,
            "suggestion": SUGGESTIONS[category],
        })
    sev_order = {"flag": 0, "warn": 1}
    results.sort(key=lambda r: (sev_order[r["severity"]], -r["size"]))
    return results


def fmt_size(unit: str, n: int) -> str:
    if unit == "lines":
        return f"{n} lines"
    if n >= 1024 * 1024:
        return f"{n / (1024 * 1024):.1f} MiB"
    if n >= 1024:
        return f"{n / 1024:.0f} KiB"
    return f"{n} B"


# Category render order: plans first because they are easiest to act on
# (mark complete, split), binary last because the action is usually
# git-lfs/.gitignore rather than editing.
RENDER_ORDER = ("plan", "source", "test", "doc", "config", "shell", "binary")


def render(results: "list[dict]") -> str:
    if not results:
        return ("## Oversized files - 0\n\n"
                "_(no tracked file exceeds its category threshold.)_\n")

    by_cat: dict[str, list[dict]] = {}
    for r in results:
        by_cat.setdefault(r["category"], []).append(r)

    out: list[str] = []
    out.append(f"## Oversized files - {len(results)}")
    out.append("")
    out.append(
        "Tracked files exceeding their per-category size threshold. "
        "Gitignored files are not scanned; files matching generated-code "
        "markers are skipped. See `scripts/find-oversized-files.py` for "
        "thresholds and skip rules."
    )
    out.append("")
    for cat in RENDER_ORDER:
        items = by_cat.get(cat, [])
        if not items:
            continue
        out.append(f"### {cat} - {len(items)}")
        out.append("")
        for r in items:
            tag = "[FLAG]" if r["severity"] == "flag" else "[warn]"
            size_s = fmt_size(r["unit"], r["size"])
            thr_s = fmt_size(
                r["unit"],
                r["flag"] if r["severity"] == "flag" else r["warn"],
            )
            out.append(
                f"- {tag} `{r['path']}` - {size_s} "
                f"(>= {r['severity']} threshold {thr_s}). "
                f"{r['suggestion']}"
            )
        out.append("")
    return "\n".join(out)


BASELINE_PATH = REPO / "scripts" / "oversized-flag-baseline.txt"


def load_baseline() -> "set[str]":
    """Return the set of paths in the ratchet baseline file."""
    if not BASELINE_PATH.exists():
        return set()
    return {
        line.strip()
        for line in BASELINE_PATH.read_text().splitlines()
        if line.strip() and not line.strip().startswith("#")
    }


def check_ratchet(results: "list[dict]") -> int:
    """Exit non-zero if any FLAG-severity file is NOT in the baseline.

    This is the CI ratchet: existing FLAG files are grandfathered in the
    baseline; any new FLAG file breaks the build.  When a flagged file is
    fixed, remove it from the baseline to lock in the improvement.

    Returns the exit code (0 = clean, 1 = new FLAG files found).
    """
    baseline = load_baseline()
    new_flags = [
        r for r in results
        if r["severity"] == "flag" and r["path"] not in baseline
    ]
    if not new_flags:
        return 0
    print("ERROR: new FLAG-severity oversized files (not in baseline):")
    for r in new_flags:
        size_s = fmt_size(r["unit"], r["size"])
        print(f"  {r['path']} ({r['category']}, {size_s})")
    print()
    print(f"Add to {BASELINE_PATH.relative_to(REPO)} to acknowledge, or split the file.")
    print("See scripts/find-oversized-files.py for thresholds.")
    return 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--json", action="store_true",
                    help="emit JSON instead of markdown")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any FLAG-severity file is not in the baseline "
                         "(CI ratchet mode)")
    args = ap.parse_args()
    results = scan()
    if args.check:
        return check_ratchet(results)
    if args.json:
        print(json.dumps(results, indent=2))
    else:
        print(render(results))
    return 0


if __name__ == "__main__":
    sys.exit(main())
