#!/usr/bin/env python3
"""Generate usecases/INDEX.md from usecases/<family>.md frontmatter.

Walks usecases/*.md (excluding INDEX.md), parses YAML frontmatter
(title/family/ids), and writes a single index pointing at each family file.
Mirrors the pattern of `scripts/generate-plans-index.py`.
"""
import os
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
USECASES = REPO / "usecases"
OUT = USECASES / "INDEX.md"

ID_RE = re.compile(r"^[A-Z]+\d+$")


def parse_frontmatter(text: str) -> dict | None:
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end < 0:
        return None
    fm: dict = {}
    for line in text[4:end].splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        value = value.strip()
        if value.startswith('"') and value.endswith('"'):
            value = value[1:-1]
        fm[key.strip()] = value
    return fm


def parse_ids_field(raw: str) -> list[str]:
    s = raw.strip()
    if s.startswith("[") and s.endswith("]"):
        s = s[1:-1]
    return [tok.strip() for tok in s.split(",") if tok.strip()]


def collect() -> list[dict]:
    out: list[dict] = []
    if not USECASES.is_dir():
        return out
    for path in sorted(USECASES.glob("*.md")):
        if path.name == "INDEX.md":
            continue
        text = path.read_text()
        fm = parse_frontmatter(text)
        if fm is None:
            print(f"ERROR: {path.relative_to(REPO)} missing frontmatter",
                  file=sys.stderr)
            sys.exit(1)
        family = fm.get("family", "")
        if not family:
            print(f"ERROR: {path.relative_to(REPO)} missing `family:`",
                  file=sys.stderr)
            sys.exit(1)
        ids = parse_ids_field(fm.get("ids", ""))
        for uid in ids:
            if not ID_RE.match(uid):
                print(f"ERROR: {path.relative_to(REPO)} has malformed id '{uid}'",
                      file=sys.stderr)
                sys.exit(1)
        out.append({
            "path": path.relative_to(USECASES).as_posix(),
            "title": fm.get("title", path.name),
            "family": family,
            "ids": ids,
        })
    return out


def render(entries: list[dict]) -> str:
    lines: list[str] = []
    lines.append("# Use Cases — Index")
    lines.append("")
    lines.append(
        "_Auto-generated by `scripts/generate-usecases-index.py` from "
        "frontmatter on `usecases/<family>.md`. Do not edit by hand — update "
        "the source files and run `make usecases-index`._"
    )
    lines.append("")
    lines.append(
        "Use cases derived from the [Master Plan](../masterplan.md). One file "
        "per family; IDs are stable and referenced from plan frontmatter as "
        "`validation: automated:<ID>`."
    )
    lines.append("")
    lines.append("| Family | File | IDs |")
    lines.append("|---|---|---|")
    total = 0
    for e in sorted(entries, key=lambda x: x["family"]):
        ids_str = ", ".join(f"`{i}`" for i in e["ids"]) if e["ids"] else "_(none)_"
        lines.append(f"| `{e['family']}` | [{e['title']}]({e['path']}) | {ids_str} |")
        total += len(e["ids"])
    lines.append("")
    lines.append(f"Total: {len(entries)} families, {total} IDs.")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    entries = collect()
    rendered = render(entries)
    OUT.write_text(rendered)
    total_ids = sum(len(e["ids"]) for e in entries)
    print(f"wrote {OUT.relative_to(REPO)} ({len(entries)} families, {total_ids} IDs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
