#!/usr/bin/env python3
"""Generate plans/INDEX.md from frontmatter on every plan file.

Walks plans/ recursively, parses YAML frontmatter (title/kind/status/owner/
validation/last-reviewed), and writes a status board grouped by kind and
status. Run via `make plans-index` or directly.
"""
import os
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PLANS = REPO / "plans"
OUT = PLANS / "INDEX.md"

VALID_PLAN_STATUSES = [
    "concept",
    "drafting",
    "planned",
    "building",
    "shipped-untested",
    "shipped-buggy",
    "shipped-validated",
    "superseded",
]
VALID_AUDIT_STATUSES = ["drafting", "open", "partially-resolved", "resolved"]
VALID_INCIDENT_STATUSES = ["open", "mitigated", "resolved"]
VALID_KINDS = {"plan", "audit", "incident"}

# Status badges for visual scanning. Pure ASCII to stay portable.
STATUS_BADGE = {
    "concept": "concept",
    "drafting": "drafting",
    "planned": "planned",
    "building": "BUILDING",
    "shipped-untested": "SHIPPED-UNTESTED",
    "shipped-buggy": "SHIPPED-BUGGY",
    "shipped-validated": "shipped",
    "superseded": "superseded",
    "open": "OPEN",
    "mitigated": "mitigated",
    "resolved": "resolved",
    "partially-resolved": "partial",
}

# Statuses that warrant attention at the top of the index.
ATTENTION_STATUSES = {"shipped-buggy", "shipped-untested", "open"}


def parse_frontmatter(text: str) -> dict | None:
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end < 0:
        return None
    block = text[4:end]
    fm = {}
    for line in block.splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        value = value.strip()
        if value.startswith('"') and value.endswith('"'):
            value = value[1:-1]
        fm[key.strip()] = value
    return fm


def collect():
    plans = []
    errors = []
    for root, _, names in os.walk(PLANS):
        for n in names:
            if not n.endswith(".md"):
                continue
            if n in ("INDEX.md", "README.md"):
                continue
            path = Path(root) / n
            text = path.read_text()
            fm = parse_frontmatter(text)
            rel = path.relative_to(PLANS).as_posix()
            if fm is None:
                errors.append(f"{rel}: missing YAML frontmatter")
                continue
            kind = fm.get("kind", "plan")
            status = fm.get("status", "")
            if kind not in VALID_KINDS:
                errors.append(f"{rel}: invalid kind '{kind}'")
            valid_for_kind = {
                "plan": VALID_PLAN_STATUSES,
                "audit": VALID_AUDIT_STATUSES,
                "incident": VALID_INCIDENT_STATUSES,
            }.get(kind, [])
            if status not in valid_for_kind:
                errors.append(f"{rel}: invalid status '{status}' for kind '{kind}'")
            plans.append((rel, fm))
    plans.sort(key=lambda x: x[0])
    return plans, errors


def write_index(plans, errors):
    lines = []
    lines.append("# Plans Index")
    lines.append("")
    lines.append(
        "_Auto-generated by `scripts/generate-plans-index.py`. "
        "Do not edit by hand — update the YAML frontmatter on individual plan "
        "files and run `make plans-index`._"
    )
    lines.append("")

    # Counts
    by_status = defaultdict(int)
    for _, fm in plans:
        by_status[fm.get("status", "?")] += 1
    lines.append("## Status counts")
    lines.append("")
    lines.append("| Status | Count |")
    lines.append("|---|---|")
    seen = set()
    ordered = []
    for status in VALID_PLAN_STATUSES + VALID_AUDIT_STATUSES + VALID_INCIDENT_STATUSES:
        if status in seen:
            continue
        seen.add(status)
        ordered.append(status)
    for status in ordered:
        if by_status.get(status):
            lines.append(f"| {STATUS_BADGE.get(status, status)} | {by_status[status]} |")
    lines.append(f"| **total** | **{len(plans)}** |")
    lines.append("")

    # Attention section
    attention = [(p, fm) for p, fm in plans if fm.get("status") in ATTENTION_STATUSES]
    if attention:
        lines.append("## Needs attention")
        lines.append("")
        lines.append("| Plan | Status | Owner | Last reviewed |")
        lines.append("|---|---|---|---|")
        for rel, fm in attention:
            title = fm.get("title", rel)
            status = fm.get("status", "?")
            owner = fm.get("owner", "unowned")
            reviewed = fm.get("last-reviewed", "?")
            lines.append(
                f"| [{title}]({rel}) | {STATUS_BADGE.get(status, status)} | {owner} | {reviewed} |"
            )
        lines.append("")

    # Group by top-level subfolder for the main listing
    by_section = defaultdict(list)
    for rel, fm in plans:
        section = rel.split("/", 1)[0]
        by_section[section].append((rel, fm))

    section_order = ["phases", "features", "audits", "incidents", "archive"]
    for section in section_order:
        if section not in by_section:
            continue
        lines.append(f"## {section}/")
        lines.append("")
        lines.append("| Plan | Status | Validation | Owner | Last reviewed |")
        lines.append("|---|---|---|---|---|")
        for rel, fm in by_section[section]:
            title = fm.get("title", rel)
            status = fm.get("status", "?")
            owner = fm.get("owner", "unowned")
            validation = fm.get("validation", "none")
            reviewed = fm.get("last-reviewed", "?")
            lines.append(
                f"| [{title}]({rel}) | {STATUS_BADGE.get(status, status)} | {validation} | {owner} | {reviewed} |"
            )
        lines.append("")

    # Footer: status vocabulary
    lines.append("## Status vocabulary")
    lines.append("")
    lines.append("**Plans (`kind: plan`):**")
    lines.append("")
    for s in VALID_PLAN_STATUSES:
        lines.append(f"- `{s}`")
    lines.append("")
    lines.append("**Audits (`kind: audit`):** " + ", ".join(f"`{s}`" for s in VALID_AUDIT_STATUSES))
    lines.append("")
    lines.append(
        "**Incidents (`kind: incident`):** " + ", ".join(f"`{s}`" for s in VALID_INCIDENT_STATUSES)
    )
    lines.append("")
    lines.append("**Validation:** `none`, `manual`, or `automated:<usecase-id>` (see `docs/usecase-validation-matrix.md`).")
    lines.append("")

    OUT.write_text("\n".join(lines))

    if errors:
        print("frontmatter validation errors:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        sys.exit(1)
    print(f"wrote {OUT.relative_to(REPO)} ({len(plans)} plans)")


if __name__ == "__main__":
    plans, errors = collect()
    write_index(plans, errors)
